MODEL_NAME = 'distilbert-base-uncased'
LOG_DIR = "./amazon"
NUM_EPOCHS = 2
BATCH_SIZE = 32
MAX_SEQ_LENGTH = 512
LEARNING_RATE = 5e-5
WEIGHT_DECAY = 1e-3
ACCUM_STEPS = 3
SEED = 42
FP_16 = dict(opt_level="O1")